# Generated by Django 6.0.5 on 2026-05-07 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Short description for the guide list')),
                ('content', models.TextField(help_text='Full content of the tutorial guide')),
                ('image_url', models.URLField(blank=True, help_text='URL to guide image', null=True)),
                ('category', models.CharField(blank=True, help_text='Optional category for organization', max_length=100, null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether the guide is visible to public')),
                ('order', models.IntegerField(default=0, help_text='Order for sorting guides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'db_table': 'tutorials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Link text/title', max_length=255)),
                ('url', models.URLField(help_text='The actual URL to link to')),
                ('description', models.TextField(blank=True, help_text='Optional description for the link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='guides.tutorial')),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'db_table': 'external_links',
                'ordering': ['id'],
            },
        ),
    ]
