# Generated by Django 6.0.5 on 2026-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload guide image (max 20MB)', null=True, upload_to='guide_images/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this guide in the hero section (only one at a time)'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for embedding', null=True),
        ),
    ]
