# Generated by Django 6.0.5 on 2026-05-08 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_remove_tutorial_image_url_tutorial_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('button_text', models.CharField(default='Get Started', help_text='Text displayed on the hero button', max_length=100)),
                ('button_url', models.URLField(default='https://example.com', help_text='External URL the hero button links to')),
                ('button_enabled', models.BooleanField(default=True, help_text='Whether to show the button in the hero section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Settings',
                'verbose_name_plural': 'Hero Settings',
                'db_table': 'hero_settings',
            },
        ),
    ]
