# Generated by Django 6.0.5 on 2026-05-08 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_herosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_url', models.URLField(blank=True, help_text='Telegram group or channel link (e.g., https://t.me/yourchannel)', null=True)),
                ('whatsapp_url', models.URLField(blank=True, help_text='WhatsApp link for messaging or group (e.g., https://wa.me/1234567890)', null=True)),
                ('show_telegram', models.BooleanField(default=False, help_text='Whether to show the Telegram icon in the navbar')),
                ('show_whatsapp', models.BooleanField(default=False, help_text='Whether to show the WhatsApp icon in the navbar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Links',
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
            },
        ),
    ]
